/*
  This class has been generated by the Code Generator
*/

/* ============================================================================
 * AGENT-EDITABLE CLASS.
 *
 * This file is generated ONCE per business object as a skeleton. PA does
 * NOT regenerate it on metadata changes — your edits are safe to keep here.
 *
 * The companion NotificationBase.java IS regenerated. Do not edit that file.
 *
 * The Code Generator comment above is a marker PA looks for; keep it. The
 * comment does NOT mean "do not edit" — for Base.java it does, for this
 * class it does not.
 * ========================================================================== */

package com.example.serviceops;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.query.Cursor;

public class Notification extends NotificationBase
{
    public Notification()
    {
        this((BusObjectConfig) null);
    }

    public Notification(BusObjectConfig config)
    {
        super(config);
    }

    /**
     * Resolve notification recipients for the given subject area.
     * Called by the BPM activity "Resolve Recipients" in the
     * NotificationDispatch process.
     */
    public static BusObjectIterator<Notification> getRecipientsForSubject(
            String subjectArea, Cursor cursor)
    {
        // TODO implement body
        return null;
    }

    /**
     * Send the notification through the channel implied by the recipient's
     * preferences. Returns "true" on success, error message otherwise.
     *
     * Wired from the BPM activity "Send Notification".
     */
    public String send(String recipientId, String channel, String payload)
    {
        // TODO implement body
        return "true";
    }
}
