/*
  This class has been generated by the Code Generator
*/

/* ============================================================================
 * GENERATOR-OWNED CLASS — DO NOT EDIT BY HAND.
 *
 * This file is regenerated every time the underlying DB metadata changes.
 * Any manual edits will be silently overwritten on the next regeneration.
 *
 * Add business logic to the companion Notification.java instead.
 *
 * AI agents: this file is denied in .claude/settings.json. If you find a
 * reason you "need" to edit it, the answer is no — the change belongs in
 * the metadata model (PA Web IDE) or in Notification.java.
 * ========================================================================== */

package com.example.serviceops;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.CustomBusObject;
import com.cordys.cpc.bsf.classinfo.ClassInfo;

public abstract class NotificationBase extends CustomBusObject
{
    private static ClassInfo s_classInfo = null;

    public static ClassInfo _getClassInfo()
    {
        if (s_classInfo == null)
        {
            s_classInfo = newClassInfo(Notification.class);
            s_classInfo.setUIDElements(new String[]{});
        }
        return s_classInfo;
    }

    public NotificationBase(BusObjectConfig config)
    {
        super(config);
    }

    // The generator writes one accessor pair per metadata field.
    // Real generated files have dozens of these.

    public String getNotificationId()       { return getStringValue("NotificationId"); }
    public void   setNotificationId(String v) { setProperty("NotificationId", v); }

    public String getRecipientId()          { return getStringValue("RecipientId"); }
    public void   setRecipientId(String v)  { setProperty("RecipientId", v); }

    public String getChannel()              { return getStringValue("Channel"); }
    public void   setChannel(String v)      { setProperty("Channel", v); }

    public String getPayload()              { return getStringValue("Payload"); }
    public void   setPayload(String v)      { setProperty("Payload", v); }

    public String getStatus()               { return getStringValue("Status"); }
    public void   setStatus(String v)       { setProperty("Status", v); }
}
